import { buildRegistryFromSchemaJson } from "./backends/schemaJson.js";
import { buildRegistryFromStructureDefinitions } from "./backends/structureDefinition.js";
import { convertSchema } from "./emit/schema.js";
import { extractClosure, type DefinitionRegistry } from "./ir/registry.js";
import { buildOperationPaths } from "./operations.js";
import { buildResourcePaths, commonSearchParameterComponents } from "./paths.js";
import {
  FHIR_VERSION_NUMBERS,
  FHIR_VERSIONS,
  type FhirVersion,
  type GenerateOptions,
  type JsonSchemaNode,
  type OpenApiDocument,
  type SourceBackend,
} from "./types.js";

function buildRegistry(fhirVersion: FhirVersion, source: SourceBackend): DefinitionRegistry {
  return source === "structure-def"
    ? buildRegistryFromStructureDefinitions(fhirVersion)
    : buildRegistryFromSchemaJson(fhirVersion);
}

function resolveResourceName(registry: DefinitionRegistry, requested: string): string {
  const match = registry.resourceNames.find(
    (name) => name.toLowerCase() === requested.toLowerCase(),
  );
  if (!match) {
    throw new Error(
      `Unknown FHIR ${registry.fhirVersion.toUpperCase()} resource: "${requested}". ` +
        `Run "fhir-oas list --fhir-version ${registry.fhirVersion}" to see available resources.`,
    );
  }
  return match;
}

/** Lists the resource type names available for a FHIR version. */
export function listResources(
  fhirVersion: FhirVersion,
  source: SourceBackend = "schema-json",
): string[] {
  assertFhirVersion(fhirVersion);
  return [...buildRegistry(fhirVersion, source).resourceNames].sort();
}

function assertFhirVersion(fhirVersion: string): asserts fhirVersion is FhirVersion {
  if (!FHIR_VERSIONS.includes(fhirVersion as FhirVersion)) {
    throw new Error(
      `Unsupported FHIR version "${fhirVersion}". Supported: ${FHIR_VERSIONS.join(", ")}`,
    );
  }
}

/**
 * Generates an OpenAPI document covering the requested FHIR resources: their
 * full schema dependency closure plus the standard FHIR RESTful interactions.
 */
export function generateOpenApi(options: GenerateOptions): OpenApiDocument {
  if (!options.resources || options.resources.length === 0) {
    throw new Error("At least one FHIR resource name is required");
  }
  assertFhirVersion(options.fhirVersion);
  const openApiVersion = options.openApiVersion ?? "3.0.3";
  if (openApiVersion !== "3.0.3" && openApiVersion !== "3.1.0") {
    throw new Error(`Unsupported OpenAPI version "${openApiVersion}". Supported: 3.0.3, 3.1.0`);
  }

  const registry = buildRegistry(options.fhirVersion, options.source ?? "schema-json");
  const resources = [...new Set(options.resources.map((r) => resolveResourceName(registry, r)))];

  const operationPaths: Record<string, JsonSchemaNode> = {};
  const operationRoots: string[] = [];
  if (options.operations) {
    const knownResources = new Set(registry.resourceNames);
    for (const resource of resources) {
      const result = buildOperationPaths(options.fhirVersion, resource, knownResources);
      Object.assign(operationPaths, result.paths);
      operationRoots.push(...result.extraSchemaRoots);
    }
  }

  // Bundle and OperationOutcome are always present: search/history responses
  // are Bundles and every error response is an OperationOutcome.
  const roots = [...new Set([...resources, "Bundle", "OperationOutcome", ...operationRoots])];
  const { schemas } = extractClosure(registry, roots, options.trim ?? {}, roots);

  const componentSchemas: Record<string, JsonSchemaNode> = {};
  const convertOptions = { noEnums: options.trim?.noEnums };
  for (const name of [...schemas.keys()].sort()) {
    componentSchemas[name] = convertSchema(schemas.get(name)!, openApiVersion, convertOptions);
  }

  const paths: Record<string, JsonSchemaNode> = {};
  for (const resource of resources) {
    Object.assign(paths, buildResourcePaths(options.fhirVersion, resource));
  }
  Object.assign(paths, operationPaths);

  const fhirNumber = FHIR_VERSION_NUMBERS[options.fhirVersion];
  const document: OpenApiDocument = {
    openapi: openApiVersion,
    info: {
      title:
        options.title ??
        `FHIR ${options.fhirVersion.toUpperCase()} REST API: ${resources.join(", ")}`,
      description:
        `OpenAPI definition of the FHIR ${options.fhirVersion.toUpperCase()} (${fhirNumber}) ` +
        `RESTful interactions and JSON schemas for: ${resources.join(", ")}. ` +
        "Generated by fhir-openapi-translator from the official HL7 FHIR definitions. " +
        "Schema validity does not imply full FHIR conformance: profiles, terminology " +
        "bindings, and FHIRPath invariants are not represented.",
      version: fhirNumber,
    },
    ...(options.baseUrl ? { servers: [{ url: options.baseUrl }] } : {}),
    tags: resources.map((resource) => ({
      name: resource,
      description: `Operations on the ${resource} resource`,
    })),
    paths,
    components: {
      parameters: commonSearchParameterComponents(),
      schemas: componentSchemas,
    },
  };
  return document;
}
